openapi: 3.1.0
info:
    title: Ersparnisse
    version: '1.0'
    description: >-
        Die Steuer-App nutzt einen simplen REST-Webservices zur Kommunikation mit dem Backend. Dieser
        ermöglicht die üblichen CRUD-Operationen zur Suche, Anzeige, und Erstellung von Einsparungsjahren, sowie zum Abspeichern der Gesamteinsparungen wobei
        jedes Einsparungsjahrjahr aus einem Jahr und den Einsparungen besteht.
    contact:
        name: Felix Rebmann
    license:
        name: CC-BY-4.0
        url: 'https://creativecommons.org/licenses/by/4.0/deed.de'
servers:
    -
        url: 'http://localhost:3000'
paths:
    /:
        get:
            tags:
                - Index
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/HATEOAS_Collection'
                                x-content-type: application/json
                    description: OK
            operationId: index
            summary: Wurzeladresse des Webservices
            description: Liefert eine HATEOAS-Übersicht aller collections
    'einsparungsjahr/{user_id}/{jahr}':
        get:
            tags:
                - Einsparungsjahr
            parameters:
                -
                    style: simple
                    explode: false
                    name: user_id
                    schema:
                        type: string
                    in: path
                    required: true
                -
                    style: simple
                    explode: false
                    name: jahr
                    schema:
                        type: number
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Einsparungsjahr'
                    description: OK
                '404':
                    description: Not Found
            operationId: getEinsparungsjahr
            summary: Einsparungsjahr lesen
            description: Liest ein einzelnes Einsparungsjahr vom Server.
            
    /gesamteinsparungen:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Gesamteinsparungen'
            tags:
                - Gesamteinsparungen
            responses:
                '201':
                    headers:
                        Location:
                            schema:
                                type: string
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Gesamteinsparungen'
                    description: Created
            operationId: createGesamteinsparungen
            summary: Gesamteinsparungen anlegen
            description: >-
                Gesamteinsparungen anlegen. Speichert die übergebenen Gesamteinsparungen in der Datenbank. Der Wert des
                Feldes "user_id" nimmt die des Feldes _id des Users.

components:
    schemas:
        HATEOAS_Collection:
            title: HATEOAS-Links einer Collection
            type: object
            properties:
                _name:
                    type: string
                query:
                    $ref: '#/components/schemas/HATEOAS_Link'
                create:
                    $ref: '#/components/schemas/HATEOAS_Link'
        HATEOAS_Resource:
            title: HATEOAS-Links einer Resource
            type: object
            properties:
                read:
                    $ref: '#/components/schemas/HATEOAS_Link'
                update:
                    $ref: '#/components/schemas/HATEOAS_Link'
                patch:
                    $ref: '#/components/schemas/HATEOAS_Link'
                delete:
                    $ref: '#/components/schemas/HATEOAS_Link'
        HATEOAS_Link:
            title: HATEOAS-Link
            type: object
            properties:
                url:
                    type: string
                method:
                    type: string
                query_params:
                    type: array
                    items:
                        type: string
        Einsparungsjahr:
            title: Einsparungsjahr
            required: []
            type: object
            properties:
                _links:
                    $ref: '#/components/schemas/HATEOAS_Resource'
                user_id:
                    type: string
                jahr:
                    type: number
                einsparungen:
                    type: number
            example:
                user_id: 6420557cd5033a24fc6777aa
                jahr: 2000
                einsparungen: 15000
                
        Gesamteinsparungen:
            title: Gesamteinsparungen
            required: []
            type: object
            properties:
                _links:
                    $ref: '#/components/schemas/HATEOAS_Resource'
                user_id:
                    type: string
                jahrbeginn:
                    type: number
                jahrende:
                    type: number
                gesamteinsparungen:
                    type: number
                
            example:
                user_id: 6420557cd5033a24fc6777aa
                jahrbeginn: 2000
                jahrende: 2002
                gesamteinsparungen: 25000
                
tags:
    -
        name: Index
    -
        name: Einsparungsjahr
    -
        name: Gesamteinsparungen
